console.log('This site was generated by Hugo.');

document.addEventListener("DOMContentLoaded", function () {
    // Fetch the JSON file containing the article data
    fetch('/index.json')
        .then(response => response.json())
        .then(data => {
            // Initialize Fuse.js
            const fuse = new Fuse(data, {
                keys: ['title', 'date', 'wokeness'],
                threshold: 0.3,
                minMatchCharLength: 2
            });

            // Get the input and search results elements
            const searchInput = document.querySelector('.main-search input');
            const searchResults = document.querySelector('.search-results');

            // Function to update search results
            function updateSearchResults() {
                const query = searchInput.value;
                if (query.trim() === '') {
                    searchResults.style.display = 'none';
                    searchResults.innerHTML = '';
                    return;
                }

                const results = fuse.search(query);
                searchResults.innerHTML = results.map(result => {
                    const item = result.item;
                    return `<a href="/${item.origin}/${item.title.toLowerCase().replace(/\s+/g, '-')}.html">${item.title}</a>`;
                }).join('');
                
                searchResults.style.display = results.length ? 'block' : 'none';
            }

            // Event listener for input changes
            searchInput.addEventListener('input', updateSearchResults);
        })
        .catch(error => console.error('Error fetching JSON:', error));
});